FROM debian:bullseye

WORKDIR /opt/facebooc

COPY . .

RUN apt-get update && \
    apt-get install -yq build-essential make libsqlite3-dev sqlite3

RUN    make all # to build the application

EXPOSE 16000

CMD bin/facebooc
